development:
  foodora_stripe_publishable_key: pk_test_4I1y5dfkMTY9tJf6VmrPXNqQ
  foodora_stripe_secret_key: sk_test_7DUIqHzH9B35a41zPbNny9pT
  foodora_mailgun_domain_url: sandboxa9188904f1e449f6b896cbd2e7c11de5.mailgun.org
  foodora_mailgun_default_smtp: postmaster@sandboxa9188904f1e449f6b896cbd2e7c11de5.mailgun.org
  foodora_mailgun_password: b5ff6ad1ddf47554d5a093fc84024f0b-770f03c4-a5b065d9
  foodora_mailgun_api_key: 9cfdea7b2cf243001f6e909e69aa18be-770f03c4-c1701fcf
  foodora_cloud_name: dxkgfamai
  foodora_cloudinary_api_key: "323441747193732"
  foodora_cloudinary_secret_key: fjRh5hq0rVARBRre2Nqvg76DdRo

test:
  foodora_stripe_publishable_key: pk_test_4I1y5dfkMTY9tJf6VmrPXNqQ
  foodora_stripe_secret_key: sk_test_7DUIqHzH9B35a41zPbNny9pT
  foodora_mailgun_domain_url: sandboxa9188904f1e449f6b896cbd2e7c11de5.mailgun.org
  foodora_mailgun_default_smtp: postmaster@sandboxa9188904f1e449f6b896cbd2e7c11de5.mailgun.org
  foodora_mailgun_password: b5ff6ad1ddf47554d5a093fc84024f0b-770f03c4-a5b065d9
  foodora_mailgun_api_key: 9cfdea7b2cf243001f6e909e69aa18be-770f03c4-c1701fcf
  foodora_cloud_name: dxkgfamai
  foodora_cloudinary_api_key: "323441747193732"
  foodora_cloudinary_secret_key: fjRh5hq0rVARBRre2Nqvg76DdRo

production:
  foodora_stripe_publishable_key: <%= ENV["FOODORA_STRIPE_PUBLISHABLE_KEY"] %>
  foodora_stripe_secret_key: <%= ENV["FOODORA_STRIPE_SECRET_KEY"] %>
  foodora_mailgun_domain_url: <%= ENV["FOODORA_MAILGUN_DOMAIN_URL"] %>
  foodora_mailgun_default_smtp: <%= ENV["FOODORA_MAILGUN_DEFAULT_SMTP"] %>
  foodora_mailgun_password: <%= ENV["FOODORA_MAILGUN_PASSWORD"] %>
  foodora_mailgun_api_key: <%= ENV["FOODORA_MAILGUN_API_KEY"] %>
  foodora_cloud_name: <%= ENV["FOODORA_CLOUD_NAME"] %>
  foodora_cloudinary_api_key: <%= ENV["FOODORA_CLOUDINARY_API_KEY"] %>
  foodora_cloudinary_secret_key: <%= ENV["FOODORA_CLOUDINARY_SECRET_KEY"] %>
